version: '3.9'

services:
  finfunapp:
    build:
      context: ./FinFunApp
      dockerfile: Dockerfile.FinFunApp
    image: finfunapp:local
    container_name: finfunapp
    networks:
      - internal-network
    ports:
      - "5001:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:5000"
      ConnectionStrings__Postgres: "Host=db;Port=5432;Username=FinFunUser;Password=BOK123;Database=FinFunDB;"
    depends_on:
      - db


  finfunclient:
    build:
      context: ./FinFunClient
      dockerfile: Dockerfile.FinFunClient
    image: finfunclient:local
    container_name: finfunclient
    networks:
      - internal-network
    depends_on:
      - finfunapp
    ports:
      - "3000:80"

  db:
    build:
        context: ./
        dockerfile: Dockerfile.DB
    image: db:local
    container_name: postgres-db
    networks:
      - internal-network
    environment:
      POSTGRES_DB: FinFunDB
      POSTGRES_USER: FinFunUser
      POSTGRES_PASSWORD: BOK123
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Optional, for local dev access

networks:
  internal-network:
    driver: bridge

volumes:
  postgres-data:
